### ISSUE TITLE
Eli Bendersky's feed clean up?

### ISSUE THREAD

**Issue by dotemacs** [paweljw/planetgolang.dev#28]
For Eli Bendersky's blog, this feed is used:

https://github.com/tomasurbanec/planetgolang.dev/blob/master/feeds.yml#L118

https://eli.thegreenplace.net/feeds/all.atom.xml

Which grabs all his blog posts. Some of which aren't `Go` related at all.
So it would be a good idea to omit the go irrelevant posts.

His blog has feeds per topic: https://eli.thegreenplace.net/feeds/

So for `go` he has two:

* https://eli.thegreenplace.net/feeds/go.atom.xml
* https://eli.thegreenplace.net/feeds/go-tooling.atom.xml

Looking at the output of them:

```
$ cat eli.thegreenplace.net-feeds-go-tooling.atom.xml.json |jq '.items[].link'
"https://eli.thegreenplace.net/2022/basic-go-tooling-for-generics/"
"https://eli.thegreenplace.net/2022/parent-links-in-go-asts/"
"https://eli.thegreenplace.net/2022/error-handling-with-go-tooling/"
"https://eli.thegreenplace.net/2022/exploring-function-parameter-types-with-go-tooling/"
"https://eli.thegreenplace.net/2021/rewriting-go-source-code-with-ast-tooling/"
"https://eli.thegreenplace.net/2020/writing-multi-package-analysis-tools-for-go/"
"https://eli.thegreenplace.net/2018/command-line-autocomplete-for-go-documentation/"
$ cat eli.thegreenplace.net-feeds-go.atom.xml.json | jq '.items[].link'
"https://eli.thegreenplace.net/2024/the-life-of-an-ollama-prompt/"
"https://eli.thegreenplace.net/2024/gemma-ollama-and-langchaingo/"
"https://eli.thegreenplace.net/2024/gemini-cli-access-gemini-models-from-the-command-line/"
"https://eli.thegreenplace.net/2024/using-gemini-models-in-go-with-langchaingo/"
"https://eli.thegreenplace.net/2024/sign-in-with-google-in-go/"
"https://eli.thegreenplace.net/2023/using-gemini-models-from-go/"
"https://eli.thegreenplace.net/2023/sign-in-with-github-in-go/"
"https://eli.thegreenplace.net/2023/using-ollama-with-langchaingo/"
"https://eli.thegreenplace.net/2023/retrieval-augmented-generation-in-go/"
"https://eli.thegreenplace.net/2023/better-http-server-routing-in-go-122/"
```

Ideally, both would be included. 

If only one was to be included, then maybe include this one: https://eli.thegreenplace.net/feeds/go.atom.xml

What do you think?

I don't think that having both of them would be "bad", since they both Go related.

Thanks

**Comment by tomasurbanec** [comment]
Hi.
It is good idea, I don't see anything bad about having two feeds from one blog. That is for now,  go and go-tooling feeds are included separately instead of "all" feed. In the future we might consider reverting it back depending on the resolution of #30.

Thanks.
